# Generated by Django 3.2 on 2022-11-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUNTH', models.CharField(max_length=70)),
                ('CodProfesional', models.IntegerField()),
                ('TipoProfesional', models.CharField(max_length=12)),
                ('imagen', models.ImageField(upload_to='profesionales')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
            },
        ),
    ]
