# Generated by Django 3.2 on 2022-11-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
